from pydantic import BaseModel, Field  # Import Field for descriptions

class QueryInput(BaseModel):
    query: str = Field("", description="The user's query input for the chatbot.")

class AugmentedResponse(BaseModel):
    query: str = Field("", description="The original query submitted by the user.")
    generated_response: str = Field("", description="The response generated by the chatbot based on the query.")

  